config/routes.rb
Questionnaire::Application.routes.draw do
  get "home/index"

  get "questions/index"
  
  get "questions/new" , :as => :new_question
  
  post "questions/new" , :as => :new_question

  get "questions/show"

  root :to => 'home#index' , :as => :root

end

app/models/common.rb
#encoding : utf-8
class Common
  #【功能】订单状态
  #【著作】crated by hxl at 2/28
  LIKES = [[""],[""],[""],[""],[""],[""],[""],[""],[],[],[],[]]
  ORDERSTATUS = [["待审核",1],["待二审",2],["待修改",3],["待外呼",4],["待配送",5],["配送中",6],["配送成功",7]]

end

app/models/question.rb
#encoding : utf-8
class Question < ActiveRecord::Base
  attr_accessible :answer1, :answer2, :answer2_remark,
    :answer3_citynum, :answer3_phonenum, :answer3_extennum, :answer4_username,
    :answer4_service, :answer5, :answer5_remark6, :answer5_remark7
  
  validate :answer2_remark_must_presence
  validate :answer1_must_11
  validates_presence_of :answer2 ,:message => "请选择"
  validates_presence_of :answer5_remark6, :if => proc{|t| t.answer5.include?("6") } ,:message => "请在备注框内填写文字"
  validates_presence_of :answer5_remark7, :if => proc{|t| t.answer5.include?("7") } ,:message => "请在备注框内填写文字"
  #  validates_presence_of :answer2_remark, :if => proc{|t| t.answer2 == "6" ||t.answer2 == "2" } ,:message => "请在备注框内填写文字"
  validates_length_of :answer3_phonenum, :minimum=> 7, :maximum => 11, :message => "区号请输入7个以上11个以内文字"
  validates_length_of :answer3_citynum, :minimum=> 3, :maximum => 5, :message => "主机号请输入3个以上5个以内文字"
  validates_format_of :answer4_username, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :message => '邮箱格式不正确'
  
  def answer2_remark_must_presence
    self.errors.add(:answer2_remark, "请在备注框内填写文字") if self.answer2_remark.blank? && (self.answer2 == "6" || self.answer2 == "2") 
  end

  def answer1_must_11
    self.errors.add(:answer1, "") if self.answer1 != "十一"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def show
  end
  
  def new
    @question = Question.new(params[:question])
    @question.answer5 = params[:ids]  || ""
    return unless request.post?
    @question.answer2 = params[:answer2]
    puts @question.answer5
    unless @question.valid?
      render :action => :new
      return
    end
    
    if @question.save
      redirect_to :action => :index
    end
    
  end
end

app/helpers/application_helper.rb
#encoding : utf-8
module ApplicationHelper
  def postion(question)
    case question.answer2
    when "1"
      then "学生"
    when "2"
      then "公务员（职务：#{question.answer2_remark}）"
    when "3"
      then "公司职员"
    when "4"
      then "自由职业者 "
    when "5"
      then "全职太太 "
    when "6"
      then "其他（#{question.answer2_remark}）"
    end
  end
  
  def like(question)
    result = ""
    if(question.answer5.include? "1")
      result += "<div>味道不好吃</div>"
    end
    if(question.answer5.include?  "2")
     result += "<div>味道一般</div>"
    end
    if(question.answer5.include? "3")
      result += "<div>价格太贵</div>"
    end
    if(question.answer5.include? "4")
      result += "<div>量太少</div>"
    end
    if(question.answer5.include? "5")
      result += "<div>平时不太吃橡皮糖(喜欢吃：#{question.answer5_remark6}）</div>"
    end
    if(question.answer5.include?  "6")
      result += "<div>还是喜欢平时吃的橡皮糖平时喜欢吃</div>"
    end
    if(question.answer5.include?  "6")
      result += "<div>其他(#{question.answer5_remark7})</div>"
    end
    return result.html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/home/index.html.erb
 <h2>系统信息</h2>
 <br></br>
 <table>
   <tr>
      <td>系统名称：问卷调查</td>
    </tr>
    <tr>
      <td>系统作者：胡晓龙</td>
    </tr>
     <tr>
       <td>发布地址：<a href="http://stormy-summer-7650.heroku.com/">http://stormy-summer-7650.heroku.com/</a></td>
    </tr>
    <tr>
      <td>源码地址：git@github.com:aabbcc456aa/questionnaire.git</td>
    </tr>
    <tr>
      <td>完成时间：近四小时</td>
    </tr>
 </table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Questionnaire</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
  <body>
    <div class="topbar">
      <div class="fill">
        <div class="container">
          <h3><a href="/">问卷调查</a></h3>
          <ul>
            <li><%= link_to "开始测试", new_question_url %></li>
            <li><%= link_to "测试记录", '/' %></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="container" style="margin-top:60px;">
      <% %w(success error info warning).each do |type| -%>
        <% if flash[type.to_sym] %>
          <div class="alert-message <%= type %>"><%= flash[type.to_sym] %><a href="#" class="close">×</a></div>
        <% end %>
      <% end -%>
      <%= yield %>
      <footer>        
        <p>Copyright © 2012-<%=DateTime.now.year%></p>
      </footer>
    </div> <!-- /container -->
  </body>
</html>

app/views/questions/back.erb
   <div class="clearfix">
    <%= f.label :name,"问题1：竞猜问答" %>
    <div class="input">
      <%= f.text_field :answer1,:class => "small"  %> 
    </div>
  </div>

<div class="clearfix">
    <%= f.label :name,"问题2：您的职业（单选）" %>
    <div class="input">
      <%= f.text_field :answer1,:class => "small"  %> 
    </div>
  </div>


<div class="clearfix">
    <%= f.label :name,"问题3：电话号码" %>
    <div class="input">
      <%= f.text_field :answer1,:class => "small"  %> 
    </div>
  </div>

<div class="clearfix">
    <%= f.label :name,"问题4：您的e-mail地址" %>
    <div class="input">
      <%= f.text_field :answer1,:class => "small"  %> 
    </div>
  </div>

<div class="clearfix">
    <%= f.label :name,"问题5：兴趣爱好（可复选）" %>
    <div class="input">
      <%= f.text_field :answer1,:class => "small"  %> 
    </div>
  </div>
<%end%>

app/views/questions/index.html.erb
<h2>测试结果</h2>

<table>
  <tr>
    <th>测试时间</th>
    <th>竞猜答案</th>
    <th>您的职业</th>
    <th>电话号码</th>
    <th>e-mail</th>
    <th>兴趣爱好</th>
  </tr>
  <% @questions.each do  |question| %>
    <tr>
      <td><%= question.created_at   %></td>
      <td><%= question.answer1 %></td>
      <td><%= postion(question) %></td>  
      <td><%= question.answer3_citynum %>-<%= question.answer3_phonenum %>-<%= question.answer3_extennum %></td>
      <td><%= question.answer4_username %></td>
      <td><%= like(question) %></td>
    </tr>
    <% end %>
  </table>

app/views/questions/new.html.erb
<h2>调查项目</h2>
<br></br>
<%= form_for @question ,:url => :new_question , :method=> :post do |f| %>
  <table class="form">
    <tr>
      <td class="index">01</td>
      <td class="question">竞猜问答</td>
      <td class="answer">
        <div id="error"><%= "正确答案：<B>「十一」</B>".html_safe if @question.errors[:answer1][0] %></div>
        <%= f.text_field :answer1,:class => "small" %> 
      </td>
    </tr>
    <tr>
      <td class="index">02</td>
      <td class="question">您的职业（单选）</td>
      <td class="answer">
         <div id="error"><%= @question.errors[:answer2][0]  %></div>
        <div id="error"><%= @question.errors[:answer2_remark][0]  %></div>
        <div> 
          <%= radio_button_tag :answer2,"1" ,@question.answer2 == "1", :class => "answer2" %>学生
        </div>  
        <div> 
          <%= radio_button_tag :answer2,"2" ,@question.answer2 == "2", :class => "answer2" %>公务员（职务：
          <%= f.text_field :answer2_remark,:class => "small" ,:disabled => !(@question.answer2 == "2"), :id => "answer2_remark_2"  %>）
        </div>  
        <div> 
          <%= radio_button_tag :answer2,"3" ,@question.answer2 == "3", :class => "answer2"  %>公司职员
        </div>  
        <div> 
          <%= radio_button_tag :answer2,"4" ,@question.answer2 == "4", :class => "answer2"  %>自由职业者
        </div> 
        <div> 
          <%= radio_button_tag :answer2,"5" ,@question.answer2 == "5", :class => "answer2"  %>全职太太
        </div>  
        <div> 
          <%= radio_button_tag :answer2,"6"  ,@question.answer2 == "6", :class => "answer2" %>其他
          <%= f.text_field :answer2_remark,:class => "small" ,:disabled => !(@question.answer2 == "6") , :id => "answer2_remark_6" %>
        </div> 
      </td>
    </tr>
    <tr>
      <td class="index">03</td>
      <td class="question">电话号码</td>
      <td class="answer">
        <div id="error"><%= @question.errors[:answer3_citynum][0]  %></div>
        <div id="error"><%= @question.errors[:answer3_phonenum][0]  %></div>
        <div> <%= f.text_field :answer3_citynum,:class => "small" ,:placeholder => "区号"   %>-
          <%= f.text_field :answer3_phonenum,:class => "small" ,:placeholder => "主机号"   %>-
          <%= f.text_field :answer3_extennum,:class => "small"  ,:placeholder => "分机号"  %></div>
      </td>
    </tr>
    <tr>
      <td class="index">04</td>
      <td class="question">您的e-mail地址</td>

      <td class="answer"> 
        <div id="error"><%= @question.errors[:answer4_username][0]  %></div>
        <%= f.text_field :answer4_username,:class => "long",:placeholder => "username@explame.com"  %></td>
    </tr>
    <tr>
      <td class="index">05</td>
      <td class="question">兴趣爱好（可复选）</td>
      <td class="answer">
        <div id="error"><%= @question.errors[:answer5_remark6][0]  %></div>
         <div id="error"><%= @question.errors[:answer5_remark7][0]  %></div>
        <div><%= check_box_tag 'ids[]', "1" ,@question.answer5.include?("1"), :class => "ids" ,:id => "ids_1"%>味道不好吃</div>
        <div><%= check_box_tag 'ids[]', "2", @question.answer5.include?("2"), :class => "ids" ,:id => "ids_2"%>味道一般</div>
        <div><%= check_box_tag 'ids[]', "3" ,@question.answer5.include?("3"), :class => "ids" ,:id => "ids_3"%>价格太贵</div>
        <div><%= check_box_tag 'ids[]', "4" ,@question.answer5.include?("4"), :class => "ids" ,:id => "ids_4"%>量太少</div>
        <div><%= check_box_tag 'ids[]', "5" ,@question.answer5.include?("5"), :class => "ids" ,:id => "ids_5"%>平时不太吃橡皮糖</div>
        <div>
          <%= check_box_tag 'ids[]', "6",@question.answer5.include?("6"), :class => "ids" ,:id => "ids_6" %>还是喜欢平时吃的橡皮糖（平时喜欢吃
          <%= f.text_field :answer5_remark6,:class => "small" ,:disabled => !@question.answer5.include?("6") , :id => "answer05_ids_6" %>）
        </div>      
        <div>
          <%= check_box_tag 'ids[]', "7" ,@question.answer5.include?("7"), :class => "ids" ,:id => "ids_7"%>
          其他<%= f.text_field :answer5_remark7,:class => "small" ,:disabled => !@question.answer5.include?("7") , :id => "answer05_ids_7"%>
        </div>
      </td>
    </tr>
  </table>
  <%= submit_tag "提交" ,:class => "btn primary" %>
<%end%>

<script type="text/javascript">
  $(".ids").click(function(){
    var id = $(this).attr("id");
    var checked = $(this).attr("checked");
    if(checked == "checked"){
      $("#answer05_" + id).attr("disabled",false);
    }
    else{
      $("#answer05_" + id).attr("disabled",true);
    }
  })
  
  $(".answer2").click(function(){
    var id = $(this).attr("id");
    if(id == "answer2_2"){
      $("#answer2_remark_2").attr("disabled",false);
    }
    else if(id == "answer2_6"){
      $("#answer2_remark_6").attr("disabled",false);
    }
    else{
      $("#answer2_remark_2").attr("disabled",true);
      $("#answer2_remark_6").attr("disabled",true);
    }
  })
</script>

<style>
  #error{
    color: red;
  }
  .form{
    background-color: #fff;

  }
  .index{
    vertical-align: middle ;
    width: 30px;
    background-color: gold;
  }
  .question{
    width: 150px;
    vertical-align: middle ;
    background-color: #ccc;
  }
  table tr td{
    margin: 5px; 10px;
  }
</style>

app/views/questions/show.html.erb
<h1>Questions#show</h1>
<p>Find me in app/views/questions/show.html.erb</p>